### ISSUE TITLE
tgz support for multiple files

### ISSUE THREAD

**Issue by btoews** [CiscoCXSecurity/QRCode-Video-Data-Exfiltration#1]
If the user drops multiple files into the browser, it would be nice if it tared and gzipped the files... This would also be cool because it would make it possible to preserve some file metadata.

**Comment by gregose** [comment]
- gzip impl in JS: https://github.com/beatgammit/gzip-js/
- tar, should be easy to impl in JS http://www.gnu.org/software/tar/manual/html_node/Standard.html as long as we can easily work with the byte arrays

**Comment by gregose** [comment]
Actually, Zip may just be easier: http://stuartk.com/jszip/

**Comment by btoews** [comment]
wow, that api is about 100 times simpler than I would have envisioned...

On Tue, Jul 17, 2012 at 11:06 PM, Greg Ose
reply@reply.github.com
wrote:

> Actually, Zip may just be easier: http://stuartk.com/jszip/
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mastahyeti/DataExfiltration/issues/1#issuecomment-7056227

## 

-Ben Toews

**Comment by btoews** [comment]
mastahyeti/DataExfiltration@cd3088db3b8ad546d11d77d3b28089376775cfe8 may or may not actually work. I don't have a USB cable with me to transfer the video...
